# Generated by Django 4.1.1 on 2022-09-21 10:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=12)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('contacted_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-contacted_on'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Gallery', validators=[django.core.validators.validate_image_file_extension])),
                ('text', models.CharField(max_length=40)),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_on'],
            },
        ),
        migrations.CreateModel(
            name='HomePosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='Home-Images', validators=[django.core.validators.validate_image_file_extension])),
                ('link', models.URLField(blank=True, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='Presskit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=50)),
                ('years_active', models.CharField(max_length=50)),
                ('origin', models.CharField(max_length=50)),
                ('bio', models.TextField()),
                ('image', models.ImageField(upload_to='Presskit', validators=[django.core.validators.validate_image_file_extension])),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50, unique=True)),
                ('city', models.CharField(max_length=50)),
                ('datetime', models.DateField()),
            ],
            options={
                'ordering': ['-datetime'],
            },
        ),
    ]
