# Generated by Django 3.2.10 on 2022-09-26 16:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('small_desc', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='Music-Images', validators=[django.core.validators.validate_image_file_extension])),
                ('music', models.FileField(upload_to='Music-Audio')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_on'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('video', models.FileField(upload_to='')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_on'],
            },
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['-uploaded_on'], 'verbose_name_plural': 'Gallery'},
        ),
        migrations.AlterModelOptions(
            name='homeposts',
            options={'ordering': ['-time'], 'verbose_name_plural': 'HomePosts'},
        ),
        migrations.AlterModelOptions(
            name='presskit',
            options={'verbose_name_plural': 'Presskit'},
        ),
        migrations.AlterModelOptions(
            name='tour',
            options={'ordering': ['-datetime'], 'verbose_name_plural': 'Tour'},
        ),
        migrations.AddField(
            model_name='presskit',
            name='presskit',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
