# Generated by Django 3.2.10 on 2022-09-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220926_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='presskit',
            name='work_profile',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
