# Generated by Django 3.2.10 on 2022-10-06 06:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_video_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeImageAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Home-Poster-Images', validators=[django.core.validators.validate_image_file_extension])),
                ('about', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'HomeImageAbout',
            },
        ),
    ]
