# Generated by Django 3.2.10 on 2022-10-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homeimageabout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='music',
            field=models.URLField(),
        ),
    ]
