# Generated by Django 3.2.10 on 2022-10-07 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20221006_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='image',
        ),
        migrations.RemoveField(
            model_name='music',
            name='small_desc',
        ),
    ]
