# Generated by Django 3.2.10 on 2022-10-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_music_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='title',
            field=models.CharField(choices=[('Spotify', 'Spotify'), ('SoundCloud', 'SoundCloud'), ('Mixcloud', 'Mixcloud')], max_length=50),
        ),
    ]
